version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "arthur@tatay.com"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "54321:80"
    depends_on:
      - postgres

# Para configurar o banco de dados acesse http://localhost:54321/browser/
# faça login com as credenciais que estão no `docker-compose` e crie um server com nome "alunos"
# Na aba de connections preencha:
# - maintenance database, username e password com o valor "root"
# - port tem o valor "5432"
# - para preencher host você precisa executar `docker-compose exec postgres sh` pra entrar no container
#   e executar `hostname -i` para pegar o host e preencha o campo de host